[package]
name = "cargo-aoc"
version = "0.1.0"
authors = ["traxys <quentin@familleboyer.net>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
color-eyre = "0.6.2"
